### ISSUE TITLE
HTTP ERROR when doing an asynchronous cone search

### ISSUE THREAD

**Issue by chenjunzhan** [MGJvanGroeningen/gaia_oc_amd#1]
![image](https://user-images.githubusercontent.com/48664039/234572230-47079d16-e30e-40ff-a05d-0878ca550521.png)

**Comment by chenjunzhan** [comment]
![image](https://user-images.githubusercontent.com/48664039/234572417-c9a579a2-a269-4dd1-99f7-b03eaccf3b05.png)
I don't know how to solve this problem, has anyone encountered a similar problem?

**Comment by MGJvanGroeningen** [comment]
Hi @chenjunzhan, thanks for your question. I don't remember seeing this before (although I may have some time ago), but the HTTP error implies it's related to the ESA Gaia archive servers. One possible problem is that your 'job results quota' is full. You can check this at https://gea.esac.esa.int/archive/ and by clicking on your profile at the top-right of the page after logging in. Another thought is that maybe you need to do something like verify your email related to your account, to get the rights for additional space of registered accounts.

**Comment by chenjunzhan** [comment]
Thank you for your help. As you said, I cleared the job result quota and solved the problem.

> Hi @chenjunzhan, thanks for your question. I don't remember seeing this before (although I may have some time ago), but the HTTP error implies it's related to the ESA Gaia archive servers. One possible problem is that your 'job results quota' is full. You can check this at https://gea.esac.esa.int/archive/ and by clicking on your profile at the top-right of the page after logging in. Another thought is that maybe you need to do something like verify your email related to your account, to get the rights for additional space of registered accounts.
Thank you for your help. As you said, I cleared the job result quota and solved the problem.

**Comment by chenjunzhan** [comment]
> Hi @chenjunzhan, thanks for your question. I don't remember seeing this before (although I may have some time ago), but the HTTP error implies it's related to the ESA Gaia archive servers. One possible problem is that your 'job results quota' is full. You can check this at https://gea.esac.esa.int/archive/ and by clicking on your profile at the top-right of the page after logging in. Another thought is that maybe you need to do something like verify your email related to your account, to get the rights for additional space of registered accounts.

Thank you for your help. As you said, I cleared the job result quota and solved the problem.
